# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-06-12 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_md',
            field=models.BooleanField(default=False, verbose_name='markdown语法'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(help_text='按住ctrl可多选', to='blog.Tag', verbose_name='标签'),
        ),
    ]
